apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-express-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-express-demo
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 5
