apiVersion: v1
kind: Service
metadata:
  name: backend-express-demo
  labels:
    app: backend-express-demo
    role: backend
    env: test
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000

  selector:
    app: backend-express-demo
    role: backend
    env: test